# Generated by Django 5.2 on 2025-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField()),
                ("desc", models.CharField()),
                (
                    "findings",
                    models.ManyToManyField(
                        related_name="definitions", to="findings.finding"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scans",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "findings",
                    models.ManyToManyField(related_name="scans", to="findings.finding"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "findings",
                    models.ManyToManyField(
                        related_name="targets", to="findings.finding"
                    ),
                ),
            ],
        ),
    ]
