# Generated by Django 5.2 on 2025-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=255)),
                ("target_id", models.CharField(blank=True, max_length=20)),
                ("definition_id", models.CharField(blank=True, max_length=20)),
                ("scans", models.JSONField(default=list, null=True)),
            ],
        ),
    ]
